---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with parameters
Parameters:
  AMI:
    Type: String
    Default: ami-a36f8dc4
  InstanceType:
    Type: String
    Default: t2.micro
  Subnet:
    Type: String
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: AMI
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: Subnet
      Tags:
      - Key: Name
        Value: learn-cloudformation-2-parameters